name: New Client Infrastructure creation
description: request Infrastructure creation for a new Client
title: "[Client Name] - Infrastructure Creation Request"
labels: [infrastructure, client]
body:
  - type: input
    id: client_code
    attributes:
      label: Client code
      description: Please provide the code of the new client.
      placeholder: e.g., ACME
    validations:
      required: true
  - type: input
    id: location
    attributes:
      label: Location
      description: Please provide the location of the new client.
      placeholder: e.g., New York
      value: Central India
    validations:
      required: true
  - type: input
    id: branch_name
    attributes:
      label: Branch_Name
      description: Please provide the branch name for the new client.
      placeholder: e.g., feature/new-client
      value: feature/new-client
    validations:
      required: true