name: Auto-dispatch infra on issue form

on:
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write 
  
jobs:
  dispatch-infra:
    # only run for your specific request template title
    if: contains(github.event.issue.title, 'Infrastructure Creation Request')
    runs-on: ubuntu-latest
    steps:
    - name: Parse issue form inputs
      id: parse
      uses: actions/github-script@v7
      with:
        script: |
          const body = context.payload.issue.body || '';

          function grab(label) {
            const patterns = [
              // ### Label \n value
              new RegExp(String.raw`^###\s*${label}\s*\r?\n+([^\r\n]+)`, 'mi'),
              // **Label** \n value
              new RegExp(String.raw`^\*\*${label}\*\*\s*\r?\n+([^\r\n]+)`, 'mi'),
              // Label: value  (same line)
              new RegExp(String.raw`^${label}\s*:\s*([^\r\n]+)`, 'mi'),
              // Label \n value  (plain)
              new RegExp(String.raw`^${label}\s*\r?\n+([^\r\n]+)`, 'mi')
            ];
            for (const re of patterns) {
              const m = body.match(re);
              if (m && m[1]) return m[1].trim();
            }
            return '';
          }

          const client_name = grab('Client Name');
          const client_code = grab('Client code');
          const location    = grab('Location');
          const branch_name   = grab('Branch Name');

          core.setOutput('client_name', client_name);
          core.setOutput('location', location);
          core.setOutput('branch_name', branch_name);
          core.setOutput('issue_api_url', context.payload.issue.url);

    - name: Update issue title with client_code
      uses: actions/github-script@v7
      with:
        script: |
          const clientCode = "${{ steps.parse.outputs.client_code }}".trim();
          const issue = context.payload.issue;

          // Format: [clientCode] - Infrastructure Creation Request
          const newTitle = `[${clientCode}] - Infrastructure Creation Request`;

          if (issue.title !== newTitle) {
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              title: newTitle
            });
            core.info(`✅ Title updated to: ${newTitle}`);
          } else {
            core.info(`ℹ️ Title already correct, skipping update.`);
          }

    - name: Dispatch infra workflow
      env:
        CLIENT_NAME: ${{ steps.parse.outputs.client_name }}
        CLIENT_CODE: ${{ steps.parse.outputs.client_code }}
        LOCATION: ${{ steps.parse.outputs.location }}
        ISSUE_API_URL: ${{ steps.parse.outputs.issue_api_url }}
        BRANCH_NAME: ${{ steps.parse.outputs.branch_name }}
      run: |
        curl -sS -f -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/AgentSprint/infra-azure/actions/workflows/new_infra.yml/dispatches \
        -d "{\"ref\":\"$BRANCH_NAME\",\"inputs\":{\"client_name\":\"$CLIENT_NAME\",\"client_code\":\"$CLIENT_CODE\",\"location\":\"$LOCATION\",\"issue_api_url\":\"$ISSUE_API_URL\"}}"

