name: Initiate New Client Infrastructure Creation

on:
  workflow_dispatch:
    inputs:
      client_code:
        description: 'Client code to deploy'
        required: true
        type: string
      location:
        description: 'Location to deploy the client code'
        required: true
        type: string
      issue_url:
        description: 'URL of the issue to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Make API call to deploy client infrastructure
        env:
          CLIENT_CODE: ${{ github.event.inputs.client_code }}
          LOCATION: ${{ github.event.inputs.location }}
          ISSUE_URL: ${{ github.event.inputs.issue_url }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/AgentSprint/infra-azure/actions/workflows/new_infra.yml/dispatches \
            -d "{\"ref\":\"main\",\"inputs\":{\"client_code\":\"$CLIENT_CODE\",\"location\":\"$LOCATION\",\"issue_url\":\"$ISSUE_URL\"}}"
